Repository chakra-ui/chakra-ui-vue, pull requests merged in 2020-03, with the labels that each got.

#51 Bugfix/story issues
  .storybook/components/Canvas.vue
  packages/chakra-ui-core/src/Progress/Progress.stories.js
  packages/chakra-ui-core/src/Radio/index.js
  packages/chakra-ui-core/src/Radio/tests/Radio.test.js
  packages/chakra-ui-core/src/Radio/tests/__snapshots__/Radio.test.js.snap
  packages/chakra-ui-core/src/RadioButtonGroup/RadioGroup.stories.js
  packages/chakra-ui-core/src/RadioButtonGroup/index.js
  packages/chakra-ui-core/src/RadioButtonGroup/tests/RadioButtonGroup.test.js
  packages/chakra-ui-core/src/RadioButtonGroup/tests/__snapshots__/RadioButtonGroup.test.js.snap
  packages/chakra-ui-core/src/Select/index.js
Labels: enhancement

#79 docs: documentation for Alert component
  packages/chakra-ui-docs/docs/alert.mdx
Labels: type: documentation 📚

#90 Release/accordion
  .github/workflows/greetings.yml
  packages/chakra-ui-core/src/CAccordion/CAccordion.js
  packages/chakra-ui-core/src/CAccordion/accessibility.md
  packages/chakra-ui-docs/components/components.js
Labels: topic: accessibility (A11y) ♿️, type: documentation 📚

#91 docs(accordion): added accordion component docs
  .github/workflows/greetings.yml
  packages/chakra-ui-core/src/CAccordion/CAccordion.js
  packages/chakra-ui-core/src/CAccordion/accessibility.md
  packages/chakra-ui-docs/components/components.js
  packages/chakra-ui-docs/components/live-editor-layout.vue
  packages/chakra-ui-docs/docs/accordion.mdx
  packages/chakra-ui-docs/layouts/default.vue
Labels: type: documentation 📚
