Repository chakra-ui/chakra-ui-vue, pull requests merged in 2020-09, with the labels that each got.

#287 fix: CReset config prop type
  packages/chakra-ui-core/src/CReset/CReset.js
Labels: status: under review 🕵🏻‍♀️

#294 fix: overflow scrolling on mobile view tables in documentation
  website/components/MDXComponents.js
  website/pages/modal.mdx
Labels: type: documentation 📚

#286 fix: Update CRadio props.value
  packages/chakra-ui-core/src/CRadio/CRadio.js
Labels: status: under review 🕵🏻‍♀️

#326 feat: add autoImport to @chakra-ui/nuxt module options
  package.json
  packages/chakra-ui-core/src/directives/chakra.directive.js
  packages/chakra-ui-nuxt/example/autoimport/layouts/default.vue
  packages/chakra-ui-nuxt/example/autoimport/nuxt.config.js
  packages/chakra-ui-nuxt/example/autoimport/pages/directive.vue
  packages/chakra-ui-nuxt/example/autoimport/pages/index.vue
  packages/chakra-ui-nuxt/example/autoimport/utils/theme.js
  packages/chakra-ui-nuxt/example/base/layouts/default.vue
  packages/chakra-ui-nuxt/example/base/nuxt.config.js
  packages/chakra-ui-nuxt/example/base/pages/directive.vue
  packages/chakra-ui-nuxt/example/base/pages/index.vue
  packages/chakra-ui-nuxt/example/base/utils/theme.js
  packages/chakra-ui-nuxt/lib/module.js
  packages/chakra-ui-nuxt/package.json
  packages/chakra-ui-nuxt/test/auto-import.spec.js
  packages/chakra-ui-nuxt/test/base.spec.js
  website/components/BottomLink.vue
  website/layouts/default.vue
  website/pages/auto-import-components.mdx
  yarn.lock
Labels: type: feature or enhancement ⚡️

#330 chore: @chakra-ui/vue@0.6.6 and @chakra-ui/nuxt@0.1.0 🎉
  .all-contributorsrc
  .storybook/components/Canvas.vue
  .storybook/config.js
  README.md
  package.json
  packages/chakra-ui-core/CHANGELOG.md
  packages/chakra-ui-core/package.json
  packages/chakra-ui-core/src/CInputGroup/CInputGroup.js
  packages/chakra-ui-core/src/CInputGroup/tests/CInputGroup.test.js
  packages/chakra-ui-core/src/CInputGroup/tests/__snapshots__/CInputGroup.test.js.snap
  packages/chakra-ui-core/src/CReset/CReset.js
  packages/chakra-ui-core/src/CReset/tests/CReset.test.js
  packages/chakra-ui-core/src/CReset/tests/__snapshots__/CReset.test.js.snap
  packages/chakra-ui-core/src/CStack/CStack.js
  packages/chakra-ui-core/src/CStack/CStack.stories.js
  packages/chakra-ui-core/src/CStack/tests/CStack.test.js
  packages/chakra-ui-core/src/CStack/tests/__snapshots__/CStack.test.js.snap
  packages/chakra-ui-core/src/config/props/props.config.js
  packages/chakra-ui-core/src/config/props/props.js
  packages/chakra-ui-core/src/directives/chakra.directive.js
  packages/chakra-ui-core/src/utils/components.js
  packages/chakra-ui-core/src/utils/styled-system.js
  packages/chakra-ui-nuxt/CHANGELOG.md
  packages/chakra-ui-nuxt/example/autoimport/layouts/default.vue
  packages/chakra-ui-nuxt/example/autoimport/nuxt.config.js
  packages/chakra-ui-nuxt/example/autoimport/pages/directive.vue
  packages/chakra-ui-nuxt/example/autoimport/pages/index.vue
  packages/chakra-ui-nuxt/example/autoimport/utils/theme.js
  packages/chakra-ui-nuxt/example/base/layouts/default.vue
  packages/chakra-ui-nuxt/example/base/nuxt.config.js
  packages/chakra-ui-nuxt/example/base/pages/directive.vue
  packages/chakra-ui-nuxt/example/base/pages/index.vue
  packages/chakra-ui-nuxt/example/base/utils/theme.js
  packages/chakra-ui-nuxt/lib/module.js
  packages/chakra-ui-nuxt/package.json
  packages/chakra-ui-nuxt/test/auto-import.spec.js
  packages/chakra-ui-nuxt/test/base.spec.js
  tests/test-utils/test-utils.js
  website/components/BottomLink.vue
  website/components/MDXComponents.js
  website/layouts/default.vue
  website/package.json
  website/pages/auto-import-components.mdx
  website/pages/list.mdx
  website/pages/stack.mdx
  website/pages/toast.mdx
  yarn.lock
Labels: type: feature or enhancement ⚡️
